spring:
  datasource:
    url: jdbc:h2:mem:chaterrodb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      enabled: true
      path: /h2
  security:
    user:
      name: admin
      password: admin